/* eslint-disable */

/**
 * This file was automatically generated by @lanelink/tools
 *
 * Using `json-schema-to-typescript`, `@redocly/openapi-core` and `prisma-kysely`.
 *
 * DO NOT MODIFY IT BY HAND. Instead, modify the openapi schemas or the `prisma.schema`
 * and re-run `@lanelink/tools generate` to regenerate this file
 * */

import type { RecipeIngredients as recipeIngredients } from '@menubook/types'
import type { Insertable, Selectable, Updateable } from 'kysely'

export type RecipeIngredients = Selectable<recipeIngredients>
export type NewRecipeIngredients = Insertable<recipeIngredients>
export type UpdateRecipeIngredients = Updateable<recipeIngredients>

export type RecipeIngredientsInsertTypes =
  | NewRecipeIngredients
  | UpdateRecipeIngredients
