/* eslint-disable */

/**
 * This file was automatically generated by @lanelink/tools
 *
 * Using `json-schema-to-typescript`, `@redocly/openapi-core` and `prisma-kysely`.
 *
 * DO NOT MODIFY IT BY HAND. Instead, modify the openapi schemas or the `prisma.schema`
 * and re-run `@lanelink/tools generate` to regenerate this file
 * */

import type { Recipe as recipe } from '@menubook/types'
import type { Insertable, Selectable, Updateable } from 'kysely'

export type Recipe = Selectable<recipe>
export type NewRecipe = Insertable<recipe>
export type UpdateRecipe = Updateable<recipe>

export type RecipeInsertTypes = NewRecipe | UpdateRecipe
