/* eslint-disable */

/**
 * This file was automatically generated by @lanelink/tools
 *
 * Using `json-schema-to-typescript`, `@redocly/openapi-core` and `prisma-kysely`.
 *
 * DO NOT MODIFY IT BY HAND. Instead, modify the openapi schemas or the `prisma.schema`
 * and re-run `@lanelink/tools generate` to regenerate this file
 * */

import type { Insertable, Selectable, Updateable } from 'kysely'
import type { Supplier as supplier } from '../../datastore/types.ts'

export type Supplier = Selectable<supplier>
export type NewSupplier = Insertable<supplier>
export type UpdateSupplier = Updateable<supplier>

export type SupplierInsertTypes = NewSupplier | UpdateSupplier
