/* eslint-disable */

/**
 * This file was automatically generated by @lanelink/tools
 *
 * Using `json-schema-to-typescript`, `@redocly/openapi-core` and `prisma-kysely`.
 *
 * DO NOT MODIFY IT BY HAND. Instead, modify the openapi schemas or the `prisma.schema`
 * and re-run `@lanelink/tools generate` to regenerate this file
 * */

export * from './Ingredient.interface'
export * from './Recipe.interface'
export * from './RecipeIngredients.interface'
export * from './Supplier.interface'
