/* eslint-disable */

/**
 * This file was automatically generated by @lanelink/tools
 *
 * Using `json-schema-to-typescript`, `@redocly/openapi-core` and `prisma-kysely`.
 *
 * DO NOT MODIFY IT BY HAND. Instead, modify the openapi schemas or the `prisma.schema`
 * and re-run `@lanelink/tools generate` to regenerate this file
 * */

import type { Insertable, Selectable, Updateable } from 'kysely'
import type { Ingredient as ingredient } from '../../datastore/types.ts'

export type Ingredient = Selectable<ingredient>
export type NewIngredient = Insertable<ingredient>
export type UpdateIngredient = Updateable<ingredient>

export type IngredientInsertTypes = NewIngredient | UpdateIngredient
